/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jniConnector */

#ifndef _Included_jniConnector
#define _Included_jniConnector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jniConnector
 * Method:    getEventRecords
 * Signature: (Ljava/lang/String;)[LeventRecord;
 */
JNIEXPORT jobjectArray JNICALL Java_jniConnector_getEventRecords
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
